### ISSUE TITLE
Image not read correctly?

### ISSUE THREAD

**Issue by PetrKryslUCSD** [simonster/NIfTI.jl#5] opened 2015-03-06 19:52 UTC
I suppose the issue has to do with the difference between 0.3 and 0.4.  In 0.3 I get

julia> using NIfTI

julia> ni=niread("Tutr012BigVolLftEar45um_periotic_bw_sub2-nii.hdr");

julia> size(ni)
(409,282,202,1)

and with 0.4 I get

julia> using NIfTI

julia> ni=niread("Tutr012BigVolLftEar45um_periotic_bw_sub2-nii.hdr");

julia> size(ni)
(409,282,0,0)

There's a bunch of warnings of deprecated features too.

Petr

**Comment by simonster** [comment] 2015-03-06 21:22
Would you mind sending the hdr to simon@simonster.com? The tests pass for me on 0.4 and I can read my volumes, so I don't really have any idea where to start.

I fixed the warnings that are actually coming from this package in cc8728e25445776800efa2f14767c2064c865468. The others are coming from StrPack and would need to be fixed there.

**Comment by PetrKryslUCSD** [comment] 2015-03-07 02:20
Hi Simon,

Here is the header file: https://www.dropbox.com/s/lzez4rt26kllnej/Tutr012BigVolLftEar45um_periotic_bw_sub2-nii.hdr?dl=0

Thanks for your help.

Petr

**Comment by simonster** [comment] 2015-03-08 16:39
I created a `test.img` file full of zeros to accompany that `hdr` and I get the correct size with `0.4.0-dev+3690`. What is your `versioninfo()`?

**Comment by PetrKryslUCSD** [comment] 2015-03-08 17:45
Hi Simon,

I have updated my installation of 0.4, unfortunately with a negative result.
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+3723 (2015-03-08 05:30 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit b80f7db* (0 days old master)
|__/                   |  x86_64-w64-mingw32

julia> workspace(); cd("C:/Users/P/Documents/GitHub/VoxelBox.jl"); include("src/
VoxelBox.jl"); cd("examples");

julia> using NIfTI

WARNING: deprecated syntax "(Type=>Integer)[]" at C:\Users\P\.julia\v0.4\StrPack
\src\StrPack.jl:25.
Use "Dict{Type,Integer}()" instead.

WARNING: deprecated syntax "{a=>b, ...}" at C:\Users\P\.julia\v0.4\StrPack\src\S
trPack.jl:110.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "[a=>b, ...]" at C:\Users\P\.julia\v0.4\StrPack\src\S
trPack.jl:300.
Use "Dict(a=>b, ...)" instead.

WARNING: deprecated syntax "[a=>b, ...]" at C:\Users\P\.julia\v0.4\StrPack\src\S
trPack.jl:405.
Use "Dict(a=>b, ...)" instead.
WARNING: Dict{K,V}(ks::AbstractArray{K},vs::AbstractArray{V}) is deprecated, use
 Dict{K,V}(zip(ks,vs)) instead.
 in depwarn at deprecated.jl:40
 in call at deprecated.jl:29
 in include at boot.jl:249
 in include_from_node1 at loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
Warning: New definition
    getindex(NIfTI.NIVolume{T,N},Any...) at C:\Users\P\.julia\v0.4\NIfTI\src\NIf
TI.jl:500
is ambiguous with:
    getindex(AbstractArray{T,N},AbstractArray{T,N}) at abstractarray.jl:478.
To fix, define
    getindex(NIfTI.NIVolume{T,N},AbstractArray{T,N})
before the new definition.

julia> ni=niread("Tutr012BigVolLftEar45um_periotic_bw_sub2-nii.hdr");

julia> size(ni.raw)
(409,282,0,0)

julia>

The entire data set has been uploaded to

https://www.dropbox.com/s/ela1dnd71ynxdcn/examples.zip?dl=0

Best regards,

Petr

**Comment by simonster** [comment] 2015-03-08 23:56
I tried on Linux, and this worked fine. I also tried on Windows, and was able to reproduce your output, but while the size is printed wrong, the values are correct, i.e., `size(ni, 3)` is 202 and `size(ni, 4)` is 1. This is a known issue caused by a bug in LLVM (JuliaLang/julia#7434) and not something that can be fixed in this package.

**Closed by simonster** 2015-03-08 23:56 UTC

**Comment by PetrKryslUCSD** [comment] 2015-03-09 02:14
Curious!  Thank you very much for your help.

Petr
